---
- name: Completely remove NGINX from Ubuntu
  hosts: webservers
  become: yes
  tasks:

    - name: Stop and disable NGINX service
      service:
        name: nginx
        state: stopped
        enabled: no

    - name: Uninstall NGINX and related packages
      apt:
        name:
          - nginx
          - nginx-common
          - nginx-core
        state: absent
        purge: yes
        update_cache: yes

    - name: Remove NGINX configuration directory
      file:
        path: /etc/nginx
        state: absent

    - name: Remove NGINX log directory
      file:
        path: /var/log/nginx
        state: absent

    - name: Remove NGINX cache (if any)
      file:
        path: /var/cache/nginx
        state: absent


